### ISSUE TITLE
你的label标签Y的数值表示什么意思？

### ISSUE THREAD

**Issue by JavisPeng** [godisboy/SNP-deep-learning#1]
通常GWAS的case-control数据，标签不都是0和1吗？我参看了你的label标签，好像都是数值。
还有，请问你这个是预测致病的SNP，还是预测样本是否犯病？

**Comment by godisboy** [comment]
@JavisPeng  恩，这里的标签的确是数值。 这个数据集是玉米的，做的是一个回归的问题，这里预测目标不是分类，是根据SNP位点信息预测玉米的性状。
